from typing import Protocol

import pandas as pd


class RulesDataPort(Protocol):
    def get_categorias_list(self) -> list[str]: ...

    def get_category_icons(self) -> dict[str, str]: ...

    def load_rules(self) -> dict: ...

    def add_rule(self, keyword: str, category: str) -> dict: ...

    def remove_rule(self, keyword: str) -> dict: ...

    def reclassify_all(self, df: pd.DataFrame) -> pd.DataFrame: ...

    def classify(self, description: str, rules: dict | None = None) -> str | None: ...

    def add_categoria(self, name: str, icon: str, gasto_real: bool) -> None: ...
